"""
Main snakefile that runs the pipeline. Run with command snakemake --snakefile Snakefile -c n,
with n being the amount of cores
"""

configfile: "config/config.yaml"

DATADIR = config["datadir"]
SAMPLES = config["samples"]
RESULTSDIR = config["resultsdir"]
REFDB = config["referenceDB"]

rule all:
    input:
        "results/images/PCA.pdf",
        "results/images/Dendrogram_and_heatmap.pdf"

include: "rules/trimmomatic.smk"
include: "rules/mapping.smk"
include: "rules/decompiling.smk"
include: "rules/expression.smk"
include: "rules/visualize.smk"
