name: STATR
channels:
  - conda-forge
  - bioconda
dependencies:
  - bedtools=2.30
  - biopython=1.81
  - bowtie2=2.4
  - bwa=0.7
  - graphviz=7.1
  - python=3.9
  - r-base=4.0
  - samtools=1.11
  - snakemake=7.22
  - trimmomatic=0.39